### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by lovewanli** [ng-matero/ng-matero#11]
使用chrome打开页面每个菜单点击多次后，等待一段时间。再次点击菜单，菜单的响应速度明显变慢，通过f11开发者工具查看 发现memory持续增加。

**Comment by lovewanli** [comment]
antv g2的问题

**Comment by nzbin** [comment]
@lovewanli 已修复，在 Angular 中初始化图表时需要使用 runOutsideAngular
