### ISSUE TITLE
新建模块建议放在app下面

### ISSUE THREAD

**Issue by archimate** [ng-matero/ng-matero#14]
![image](https://user-images.githubusercontent.com/8114237/68448363-3df59300-021e-11ea-890a-8d5c36628969.png)
每个模块在app下面一个目录多好， 图片这样感觉怪怪的

**Comment by nzbin** [comment]
基于 schematics 创建的模块为路由模块，其中包含路由注册等一些自动化配置，如果需要在 app 目录创建模块，可以直接使用 `ng g module`
