### ISSUE TITLE
The interaction with the application is a bit slow.

### ISSUE THREAD

**Issue by catapulveda** [ng-matero/ng-matero#15]
Hi, Excellent job.
I would like to tell you that browsing the application is a bit slow. It takes 2 or 3 seconds sometimes to access other routes. What can be?

**Comment by nzbin** [comment]
> Hi, Excellent job.
> I would like to tell you that browsing the application is a bit slow. It takes 2 or 3 seconds sometimes to access other routes. What can be?

Because the route is a lazy module, when you first open it, it will take some time to load the js.

**Comment by nzbin** [comment]
@catapulveda I have find the issue, it's caused by the dashboard chart. I have fixed it, thanks for your advice.🤝

**Comment by catapulveda** [comment]
Good job, I will test the application performance when accessing the routes.
