### ISSUE TITLE
Error Menu

### ISSUE THREAD

**Issue by ANDRESFCC** [ng-matero/ng-matero#158]
The JSON of the menu is not generated automatically and when adding it manually the links appear as:

menu.page
menu.pag-tow

What I can do?

**Comment by nzbin** [comment]
Add your menu item to the i18n files as the following format
https://github.com/ng-matero/ng-matero/blob/705c6b9933683f7b563e4d194a3aa563c03bdd55/src/assets/i18n/en-US.json#L2-L80

**Comment by ANDRESFCC** [comment]
> You should add menu item to the i18n files as the following format
> https://github.com/ng-matero/ng-matero/blob/705c6b9933683f7b563e4d194a3aa563c03bdd55/src/assets/i18n/en-US.json#L2-L80


Thank you very much it worked without problems
