### ISSUE TITLE
Got an error when follow installation instruction

### ISSUE THREAD

**Issue by mrkimmy** [ng-matero/ng-matero#17]
I followed installation instruction. When I ran command

`ng add ng-matero`

I got an error below

> Cannot find module '@schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript'

![image](https://user-images.githubusercontent.com/14201370/69217123-66777880-0ba0-11ea-95b7-7be40dcb1106.png)

Could you suggest how to solve this error. Thank you.

**Comment by mrkimmy** [comment]
I found solution.

I install @angular/cli@8.2.2 and create new project with angular 8.2.2 
Then install @schematics/angular@8.2.0 before run ng add ng-matero

below are command I used.

`npm install @angular/cli@8.2.2`
`ng new [project_name]`
`cd [project_name]`
`npm install @schematics/angular@8.2.0`
`ng add ng-matero`

All errors gone and my project run properly.

**Comment by nzbin** [comment]
@mrkimmy 👍
