### ISSUE TITLE
sidemenu not working when using a prefix

### ISSUE THREAD

**Issue by petasis** [ng-matero/ng-matero#189]
Hi all,

If the `menu.json` contains a prefix in routes, sidemenu does not work.
For example, this `menu.json`:
```
{
  "menu": [{
      "route": "app/dashboard",
      "name": "dashboard",
      "type": "link",
      "icon": "dashboard"
    }]
}
```

A simple fix I have given to my project is here: https://github.com/iit-Demokritos/clarin-el-annotation-tool/commit/0ccfb576a8e4d7ea60816a512b5c3a6b368f132d

**Comment by nzbin** [comment]
It's similar to #27, you can try `"type": "extLink"`. But I don't recommend to use a absolute path, please check the [docs](https://nzbin.gitbook.io/ng-matero/v/en/theming/menu#route-path).

**Comment by nzbin** [comment]
It's similar to #21, you can try `extLink` type. 
```json
{
  "menu": [{
      "route": "app/dashboard",
      "name": "dashboard",
      "type": "extLink",
      "icon": "dashboard"
    }]
}
```
But I don't recommend to use a absolute path, please check the [docs](https://nzbin.gitbook.io/ng-matero/v/en/theming/menu#route-path).
