### ISSUE TITLE
Advanced search table is not taking into account [length] config

### ISSUE THREAD

**Issue by saurabh1234** [ng-matero/ng-matero#20]
For the below html and config even if you pass `[length]` different than `[data]` _size_ has no effect.

```
<mtx-grid
      *ngIf="list.length > 0"
      class="mat-elevation-z1"
      [data]="list"
      [columns]="gridColumns"
      [length]="total"
      [loading]="isLoading"
      [pageIndex]="query.page"
      [pageSize]="query.limit"
      [pageSizeOptions]="[5, 10, 20, 100]"
      (page)="getNextPage($event)"
      [frontPage]="true"
      (changeSelect)="changeSelect($event)"
    >
```

Example:

      [length]="total" // 20
      [data]="list" // list.length = 5

### Current behaviour
![image](https://user-images.githubusercontent.com/488160/71766752-9639d000-2f03-11ea-85a5-4e3a456c1e4a.png)

### Correct behaviour
**1-5 of 20** and arrow bar activated.

**Comment by nzbin** [comment]
try `[frontPage]="false"`?

**Comment by saurabh1234** [comment]
Not working unfortunately.

**Comment by nzbin** [comment]
look at the [advanced table example](https://ng-matero.github.io/ng-matero/#/tables/advanced)

**Comment by nzbin** [comment]
@saurabh1234 Are you have any questions? Can I close the issue?

**Comment by saurabh1234** [comment]
Yes we can close this one. Many thanks.
