### ISSUE TITLE
menu routing using absolute path

### ISSUE THREAD

**Issue by grantpullen** [ng-matero/ng-matero#21]
Thanks for the great project, 
I have a question/issue
Within the menu 'menu.json' I need the "children" nodes to route to different absolute paths?
e.g.
`"children": [
        {
          "state": /organizations/manage-organizations",
          "name": "Manage",
          "icon": "people",
          "type": "link"
        },`

Is this possible since  setting an empty "state" on the parent menu item does not work
Many thanks

**Comment by nzbin** [comment]
Can you give me a whole json file?

**Comment by grantpullen** [comment]
> 
> 
> Can you give me a whole json file?
Thanks for your response, and please find below the menu.json
I suggest (if possible) that if a state starts with a leading '/' it should be treated as an absolute path. 


`
{
  "menu": [
    {
      "state": "dashboard",
      "name": "Dashboard",
      "type": "link",
      "icon": "dashboard"
    },
    {
      "state": "",
      "name": "Organization",
      "type": "sub",
      "icon": "account_balance",
      "children": [
        {
          "state": "/organizations/manage-organizations",
          "name": "Manage Organization",
          "type": "link"
        },
        {
          "state": "/organizations/users",
          "name": "Manage Users",
          "icon": "people",
          "type": "link"
        }
      ]
    }
  ]
}


`

**Comment by nzbin** [comment]
I have improved the menu state, you can update the [files](https://github.com/ng-matero/ng-matero/tree/master/src/app/theme/admin-layout/sidemenu), but I'm not recommended that you use the path above. In complicated situations, you can use `extLink` type.

**Comment by grantpullen** [comment]
Many thanks
