### ISSUE TITLE
Cannot compile with AOT & compilationMode=partial

### ISSUE THREAD

**Issue by petasis** [ng-matero/ng-matero#211]
Hi all,

It seems that there is a cycle in theme/topmenu/topmenu-panel.component.ts. It is imported by theme/topmenu/topmenu.component.ts, and imports again theme/topmenu/topmenu.component.ts, just to get the TopmenuState interface.

Can this interface be placed somewhere else?

**Comment by nzbin** [comment]
What version you use?
