### ISSUE TITLE
feat(Theme customization): Customizing Sidebar Menu and Header parts separately

### ISSUE THREAD

**Issue by Raise-Exception** [ng-matero/ng-matero#219]
How to achieve below design with theme customization?

![image](https://user-images.githubusercontent.com/34378158/131252668-c58ee962-b145-40df-aa65-b4a49f20471d.png)

**Comment by nzbin** [comment]
Do you mean the body color?

**Comment by Raise-Exception** [comment]
Each parts ( Sidebar, Toolbar and Body sections) individually

**Comment by nzbin** [comment]
You can modify the default app settings or app theme styles.

https://github.com/ng-matero/ng-matero/blob/master/src/app/core/settings.ts#L13-L23

https://github.com/ng-matero/ng-matero/blob/master/src/styles/themes.scss
