### ISSUE TITLE
How to make the below mat-card fixed when user scrolls

### ISSUE THREAD

**Issue by saurabh1234** [ng-matero/ng-matero#22]
can you please tell me the css for If i want to make the below shown mat-card fixed and if the content is more than allow scroll within the content size. Many thanks for the great project.

![image](https://user-images.githubusercontent.com/488160/73119243-4036d600-3f5f-11ea-875f-355bbda24fcf.png)

**Comment by nzbin** [comment]
Fix the tab group height? You can just set a height attribute in tab group content.

**Comment by saurabh1234** [comment]
No i mean fix the right side `mat-card ` itself .. :) Many thanks in advance.
