### ISSUE TITLE
How can I setup my api jwt autherized on v12

### ISSUE THREAD

**Issue by chayayol** [ng-matero/ng-matero#229]
How can I setup my api jwt autherized on v12?
Now, I place my api url to login component, and then I get 401 error.
For this case I can get autherized response on REST Client but it's fail on ng-matero.
Please you recomment.

**Comment by nzbin** [comment]
How do you create the project? `ng add ng-matero` or cloned repo?

**Comment by chayayol** [comment]
I am download and extract zip file. and then run npm install.

**Comment by nzbin** [comment]
You should remove [demo codes](https://github.com/ng-matero/ng-matero/blob/master/src/app/app.module.ts#L51-L55) and checkout the [`core/authentication`](https://github.com/ng-matero/ng-matero/blob/master/src/app/core/authentication)

**Comment by chayayol** [comment]
thanks, I am try.
