### ISSUE TITLE
可以支持使用OpenAPI3.0的schema来生成http api吗？

### ISSUE THREAD

**Issue by Frodez** [ng-matero/ng-matero#23]
因为OpenAPI3.0的schema描述api很方便，而且ng也有一些支持使用它生成api的工具（比如 https://github.com/cyclosproject/ng-swagger-gen ），所以如果能添加根据schema生成api的工具就更好了。
ng水平很差，ts水平很差，所以没法自己写，抱歉。。。

**Comment by damingerdai** [comment]
描述api不应该是后端提供吗？？？？

**Comment by Frodez** [comment]
> 描述api不应该是后端提供吗？？？？

这里说的api是指前端访问后端endpoint的http api，就是后端开发了接口，前端要访问这个接口。后端endpoint对应的schema已经生成好了，如果有个方便的途径，根据schema来生成访问后端endpoint的http api，就能少花很多功夫。
而且schema里还描述了后端传过来的数据格式，是可以根据数据格式来生成ts的类型的。

**Comment by nzbin** [comment]
使用 [ng-openapi-gen](https://github.com/cyclosproject/ng-openapi-gen) 即可
