### ISSUE TITLE
Auto close side menu when click on link type item in mobile view

### ISSUE THREAD

**Issue by xiangboy** [ng-matero/ng-matero#230]
Is there a way to configure or change to allow auto close of the side menu when click on the link type menu item that route to a page when in mobile view?

**Comment by nzbin** [comment]
It's very easy, you can add your own click logic [at this position](https://github.com/ng-matero/ng-matero/blob/master/src/app/theme/sidemenu/sidemenu.component.html#L15).

**Comment by xiangboy** [comment]
> It's very easy, you can add your own click logic [at this position](https://github.com/ng-matero/ng-matero/blob/master/src/app/theme/sidemenu/sidemenu.component.html#L15).

Thanks for the guide.

**Comment by nzbin** [comment]
I have fixed this issue, thanks for your advice.
