### ISSUE TITLE
Feature: Parent-Child Table Grid

### ISSUE THREAD

**Issue by TejasCMehta** [ng-matero/ng-matero#24]
It will be great if we can have Parent-Child Table Grid for enterprise level usage.

**Comment by nzbin** [comment]
@TejasCMehta Can you give me a Parent-Child Table Grid example?

**Comment by TejasCMehta** [comment]
> @TejasCMehta Can you give me a Parent-Child Table Grid example? I will redesign the data grid.
something inspired by below links
https://dribbble.com/shots/2971879-SEO-PCC-Reports-Dashboard
https://dribbble.com/shots/6628618-Savings-Page/attachments/1416587
https://dribbble.com/shots/5815842-New-Invoice-InNinja/attachments/1253986

**Comment by nzbin** [comment]
@TejasCMehta I have refacted the data grid, it support parent-child table now. [View Demos](https://ng-matero.github.io/extensions/data-grid)

**Comment by TejasCMehta** [comment]
@nzbin  Brilliant work!

How can we have filter/search options like below in this grid?

![image](https://user-images.githubusercontent.com/5519037/79062830-1c13a700-7cbb-11ea-86ab-d4c1a19c83f4.png)

**Comment by nzbin** [comment]
@TejasCMehta 
I think it‘s not necessarily integrate the search into the grid and you can implement the search by yourself. I aim to add the filter option at next version. You can submit issues on [Extensions Repo](https://github.com/ng-matero/extensions/issues). I will close the issue.
