### ISSUE TITLE
How to support JWT authentication?

### ISSUE THREAD

**Issue by petasis** [ng-matero/ng-matero#246]
Hi all,

I am trying to authenticate with a JWT login service, but I do not know how to store the refresh token (to use it in refresh()).

**Comment by nzbin** [comment]
I think you should do nothing. The project initially uses JWT authentication, you can check the [files](https://github.com/ng-matero/ng-matero/tree/master/src/app/core/authentication).

**Comment by petasis** [comment]
I am not sure how it works then. It does not save the refresh token, only the access one.

**Comment by petasis** [comment]
For example, Django through the https://github.com/jazzband/djangorestframework-simplejwt plugin, during login, it generates two tokens: an access one (which expires after 20 minutes) and a refresh token (which expires after 14 days, and must be used to obtain a new access token). Since ng-matero only stores a single key, I provide the access token, But refresh cannot work.

**Comment by nzbin** [comment]
I think you can save the refresh token in the following method and use with interceptors.
https://github.com/ng-matero/ng-matero/blob/a40842944f2310c191f412ef85b14542120fae14/src/app/core/authentication/token.service.ts#L71-L80
