### ISSUE TITLE
Feature:  Can we have angular fullcalendar with material design

### ISSUE THREAD

**Issue by TejasCMehta** [ng-matero/ng-matero#25]
This app is more better then any other paid template. Mordern  and updated. I tried to add `https://github.com/fullcalendar/fullcalendar-angular` in project but stuck in showing popover on events with details. If you can add this library in current project with material theme then it will look awesome.

Let me know what you think, Angular 9 is still not supported in fullcalendar as of now.

**Comment by nzbin** [comment]
Thanks for your advice, I will try it.

**Comment by nzbin** [comment]
@TejasCMehta 
You can try the [angular-calendar](https://github.com/mattlewis92/angular-calendar). I will integrate it in the near future.

**Comment by TejasCMehta** [comment]
@nzbin I think angular full-calendar has more feature and it look like
google calendar so I like it most.
