### ISSUE TITLE
Refreshed token 

### ISSUE THREAD

**Issue by alhdo** [ng-matero/ng-matero#291]
I am trying to use ng-matero. However angular keep sending get request to get the backend to get the refreshed token but i need it to be post and can't seem to find where the request is made. I already check all the file in core folder they are all alright.
Please help.

**Comment by nzbin** [comment]
Can you provide some codes to test?

**Comment by alhdo** [comment]
`export class LoginService {
  constructor(protected http: HttpClient) {}

  login(email: string, password: string, rememberMe = false) {
    return this.http.post<TokenResponse | any>('/auth/login/', {
      username: email,
      password,
      remember_me: rememberMe,
    });
  }

  refresh(token: string) {
    return this.http.post<TokenResponse | any>('/auth/login/refresh', {
      refresh: token
    });
  }

  logout() {
    return this.http.post('/auth/logout', {});
  }

  me() {
    return this.http.get('/profile');
  }

  menu() {
    return this.http.get('assets/data/menu.json?_t=' + Date.now());
  }
}`

Here is my loginService. 
The problem is not the code itself. i use the base ng-matero with normal core and login. But somehow in a place i can't find a  GET request is being made in background to refresh the token when the method should be POST.

**Comment by recca0120** [comment]
```ts
export class LoginService {
  constructor(protected http: HttpClient) {}

  login(email: string, password: string, rememberMe = false) {
    return this.http.post<TokenResponse | any>('/auth/login/', {
      username: email,
      password,
      remember_me: rememberMe,
    });
  }

  refresh(token: string) {
    // try get method here
    return this.http.get<TokenResponse | any>('/auth/login/refresh', {
      refresh: token
    });
  }

  logout() {
    return this.http.post('/auth/logout', {});
  }

  me() {
    return this.http.get('/profile');
  }

  menu() {
    return this.http.get('assets/data/menu.json?_t=' + Date.now());
  }
}
```

**Comment by alhdo** [comment]
Actuallly i want it to be POST request not GET
