### ISSUE TITLE
using app.component.html 

### ISSUE THREAD

**Issue by yuvallavi2** [ng-matero/ng-matero#33]
Hi 

I have a need to put some other logic in my application,
so I try to do the following 

<div>
my code here.... 
  <router-outlet></router-outlet>
</div>

but when I do this the the left menu is presented based on the content and not on the full screen,

why?

thanks,

**Comment by nzbin** [comment]
Can you give some details?

**Comment by yuvallavi2** [comment]
I need to start my project like this,

<div>
    <magic-root></magic-root>
    <router-outlet></router-outlet>
</div>

for that I changed the app.component.ts to use templateUrl: './app.component.html',

my code <magic-root></magic-root> is not adding anything to the UI,
but what I see is that if I run your project even without my code (<magic-root></magic-root>),
the left menu panel is not presented in the right way,
you can do a quick test and just move the router-outlet to the html and put it inside a div

**Comment by nzbin** [comment]
I create a new project with `ng add ng-matero`. Just move the router-outlet to the html and put it inside a div, but I can't reproduce your issue.

**Comment by yuvallavi2** [comment]
thanks for trying,
I will recheck my code and see if for some reason my code do have an effect
on the div setting
