### ISSUE TITLE
Using ng-matero with Nx Workspace

### ISSUE THREAD

**Issue by JatinChimote** [ng-matero/ng-matero#364]
Hello,

I have setup a Nx mono repo and I am trying to use "npx nx g ng-matero:ng-add --project=my-ui"
However, I get this error :

PS D:\platform\workspace> npx nx g ng-matero:ng-add --project=my-ui
√ Choose a prebuilt layout template: · static
√ Choose a prebuilt navigation type: · side
√ Choose a prebuilt theme style: · light
√ Choose a prebuilt direction option: · ltr
√ Set up browser animations for Angular Material? (Y/n) · true
✔ Packages installed successfully.
[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
    Your project is not using the default builders for "test". This means that we cannot add the configured theme to the "test" target.
SchematicsException [Error]: Could not read Angular module file: /apps/my-ui/src/app/app.module.ts
    at hasNgModuleImport (D:\platform\workspace\node_modules\@angular\cdk\schematics\utils\ast\ng-module-imports.js:19:15)
    at D:\platform\workspace\node_modules\ng-matero\ng-add\setup-project.js:68:52
    at Generator.next (<anonymous>)
    at fulfilled (D:\platform\workspace\node_modules\ng-matero\ng-add\setup-project.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Could not read Angular module file: /apps/my-ui/src/app/app.module.ts

Any help or pointers on this topic would be really useful.

**Comment by nzbin** [comment]
duplicate with #351
