### ISSUE TITLE
where i can put base url for my API

### ISSUE THREAD

**Issue by hanafiahtkj** [ng-matero/ng-matero#391]
i'am sorry, anyone can help me, i just learn angular. please help me

**Comment by nzbin** [comment]
In most cases, it's usually using a relative path. But if you need a base url, you can set it in the environment variable.

For development
https://github.com/ng-matero/ng-matero/blob/master/src/environments/environment.ts

For production
https://github.com/ng-matero/ng-matero/blob/master/src/environments/environment.prod.ts

**Comment by agungdh** [comment]
hello, i have problem with base url interceptor. when i set the base url to my api endpoint, the i18n translation and menu json failed to get because it use httpclient to get them.
http://localhost:8000/api/data/menu.json?_t=1719824114579
http://localhost:8000/api/i18n/en-US.json
