### ISSUE TITLE
Create a component without dashboard layout

### ISSUE THREAD

**Issue by syeltzeen** [ng-matero/ng-matero#393]
Hi there quick question,

How can i create a component without a layout?

For example i created a component using this:

ng g ng-matero:page landing-page -m=landing-page

Thank You.

**Comment by nzbin** [comment]
I'm not quite understand. If you use the following schematics:

```bash
ng g ng-matero:page landing-page -m=landing-page
```

The created component will look like this, do you mean to remove the `page-header`?

```html
<page-header></page-header>

<p>landing-page works!</p>
```

**Comment by nzbin** [comment]
The ng-matero schematics don't support that. In fact, you can use the original [Angular CLI](https://angular.io/cli/generate) schematics.
