### ISSUE TITLE
Adding ng-matero to multi project under a workspace not working.

### ISSUE THREAD

**Issue by parchik** [ng-matero/ng-matero#395]
I am using Angular CLI: 14.0.6
On performing the following sequence:

ng new myworkspace --create-application=false
cd .\myworkspace
ng generate application projectA
ng generate application projectB
ng add ng-matero --project=projectA

? Choose a prebuilt layout template: Dynamic
? Choose a prebuilt navigation type: Side Navigation
? Choose a prebuilt theme style: Auto
? Choose a prebuilt direction option: LTR
? Set up browser animations for Angular Material? Yes
UPDATE package.json (1119 bytes)
✔ Packages installed successfully.

At the end the message is:

A merge conflicted on path "/tsconfig.json".

"ng-matero"  is added to the file package.json
But nothing is added to the project as happens is single ng-matero project.

**Comment by nzbin** [comment]
duplicate with #47
