### ISSUE TITLE
Features for mtx-grid  

### ISSUE THREAD

**Issue by panakour** [ng-matero/ng-matero#41]
Some features that exist in material table is missing from `mtx-grid  ` like:

- Footer row
- Sticky Rows and Columns
- Multiple header columns (look at the bellow picture using native angular material table):

![image](https://user-images.githubusercontent.com/12927166/80282896-a547c680-871c-11ea-9ccb-a03955b069b0.png)

**Comment by nzbin** [comment]
https://github.com/ng-matero/extensions/issues/4
Please submit related issues on extensions repo.

**Comment by panakour** [comment]
Ι didn't notice this thank you.
