### ISSUE TITLE
after change theme still light theme for mat menu

### ISSUE THREAD

**Issue by gacekm** [ng-matero/ng-matero#42]
<img width="102" alt="image" src="https://user-images.githubusercontent.com/5834314/80353698-00410100-8876-11ea-962e-4c0ab3bfe840.PNG">

how can i fix it?

**Comment by nzbin** [comment]
https://github.com/ng-matero/ng-matero/blob/cd8e905e9f90dd8cd71533fe00008b15e4d79b6f/src/app/theme/admin-layout/admin-layout.component.ts#L134

**Comment by gacekm** [comment]
thanks a lot
