### ISSUE TITLE
Cannot compile under Angular 13...

### ISSUE THREAD

**Issue by petasis** [ng-matero/ng-matero#430]
Hi all,

Why I am getting these errors?

```
core/authentication/token.ts:38:21 - error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.

38     return timeLeft((this.exp ?? 0) - 5);
```
`this.exp` seems to can also be `void`.

How can I fix this?

(I get the same error also on line 46 of the same file:
```
return this.exp !== undefined && this.exp - currentTimestamp() <= 0;
```
)

**Comment by nzbin** [comment]
Which version do you use?

**Comment by petasis** [comment]
Angular CLI: 14.2.3
Node: 16.14.0
Package Manager: npm 8.3.1 
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1402.3 (cli-only)
@angular-devkit/core         14.2.3 (cli-only)
@angular-devkit/schematics   14.2.3 (cli-only)
@schematics/angular          14.2.3 (cli-only)
