### ISSUE TITLE
[Question] TailwindCSS

### ISSUE THREAD

**Issue by nckenn** [ng-matero/ng-matero#442]
is it ok to add tailwindcss?

**Comment by nzbin** [comment]
Of course, you can add tailwindcss or any other libraries by yourself.

In fact, the ng-matero has provided a lot of useful css helpers and you can also customize them to your needs.

👉 [online demo](https://ng-matero.github.io/ng-matero/utilities/css-helpers)

👉 [source codes](https://github.com/ng-matero/ng-matero/tree/master/src/styles/helpers)

**Comment by nckenn** [comment]
> Of course, you can add tailwindcss or any other libraries by yourself.
> 
> In fact, the ng-matero has provided a lot of useful css helpers and you can also customize them to your needs.
> 
> 👉 [online demo](https://ng-matero.github.io/ng-matero/utilities/css-helpers)
> 
> 👉 [source codes](https://github.com/ng-matero/ng-matero/tree/master/src/styles/helpers)

Thanks
