### ISSUE TITLE
Sidenav issue 

### ISSUE THREAD

**Issue by emaradevska** [ng-matero/ng-matero#453]
Hi all,

After login, every click on the navigation opens the right page and the sub menu is expended and the menu item is marked as active.
After page refresh I noticed that the submenu is not expended from the previously opened menu item. If I click again, it's expended and the menu item is shown as active.

From inspect element I noticed that the li element from the sub loses class "open" after refresh.

If you can, I could really use some help for this one.

Thanks in advanced and let me know if you need more info

**Comment by nzbin** [comment]
Do you check the [docs for menu](https://nzbin.gitbook.io/ng-matero/v/en-2/theming/menu)?

**Comment by emaradevska** [comment]
> 

Yes I did, I have that. The menu works good initially, on the refresh the css class is lost, and the menu is closed (should remain the expand from before)

**Comment by nzbin** [comment]
Can you give me an online route to test?

**Comment by emaradevska** [comment]
> Can you give me an online route to test?

Unfortunately I can't share. Is there a way I can set sub menu expand by default? Now initially they are all closed

**Comment by nzbin** [comment]
What I mean is the online site. You can test the menu and give me a link that work incorrectly.
https://ng-matero.github.io/ng-matero/design/colors

In the other hand, the project is an admin template. You can change anything by yourself. Here is the menu codes.
https://github.com/ng-matero/ng-matero/tree/master/src/app/theme/sidemenu

**Comment by emaradevska** [comment]
> What I mean is the online site. You can test the menu and give me a link that work incorrectly. https://ng-matero.github.io/ng-matero/design/colors
> 
> In the other hand, the project is an admin template. You can change anything by yourself. Here is the menu codes. https://github.com/ng-matero/ng-matero/tree/master/src/app/theme/sidemenu

I tried before to break, but I failed. If there is a way to change the menu by default, that would be helpful too. I will have to keep the state for other reasons as well
