### ISSUE TITLE
Refresh Token not working

### ISSUE THREAD

**Issue by sateeshn2507** [ng-matero/ng-matero#454]
Hi, 
I am trying to get the refresh token from one of our API endpoint. 
But the refresh method in login.service.ts is never called. I just added my endpoint in the refresh method.
Can some one please let me know that when this refresh method will be called?
Also please let me know where to implement refresh token functionality(if required) i.e in token-interceptor.ts file or error-interceptor.ts file

**Comment by nckenn** [comment]
Can we implement it in HttpInterceptor?

**Comment by seyfer** [comment]
it works very well, but if you need to send refresh_token to BE API instead of access_token, add these changes to `token-interceptor.ts`

```
if (this.tokenService.valid() && this.shouldAppendToken(request.url)) {
      // send refresh token instead of access token
      const token = request.url.includes('/auth/refresh')
        ? this.tokenService.getBearerRefreshToken()
        : this.tokenService.getBearerToken();

      return next
        .handle(
          request.clone({
            headers: request.headers.append('Authorization', token || ''),
            withCredentials: true,
          }),
        )
```

and in `token.ts`

```
getBearerRefreshToken(): string {
    return this.refresh_token
      ? [capitalize(this.token_type), this.refresh_token].join(' ').trim()
      : '';
  }
```
