### ISSUE TITLE
DB connectivity for login

### ISSUE THREAD

**Issue by Aswin-coder** [ng-matero/ng-matero#457]
Please tell me how can i add db connection for login
i already have database but dont know where to use it

**Comment by nzbin** [comment]
I don't quite understand your issue.

**Comment by Aswin-coder** [comment]
U have declared the user names and passwords for login as static hard code
directly in tha code
But I want it to be in database

**Comment by nzbin** [comment]
Please check the login service and implement the logic by yourself.
https://github.com/ng-matero/ng-matero/blob/1345ccf3a35a4dcfdd65e77e6a2a48f453750c6a/src/app/core/authentication/login.service.ts#L13-L15

**Comment by nckenn** [comment]
> Please tell me how can i add db connection for login i already have database but dont know where to use it

In order to use your own database, you need a backend for it like PHP, Node, RoR, Python, etc.

Since this template is for frontend use only, you must create your own API and connect it using the HTTP client provided by Angular.
