### ISSUE TITLE
[V10] Roadmap

### ISSUE THREAD

**Issue by nzbin** [ng-matero/ng-matero#46]
- [x] Update to Angular v10 and Material v10 
- [x] authentication
- [x] http interceptors
- [x] permissions
- [x] more examples
  - [x] datetimepicker

**Comment by ewalddieser** [comment]
Will the compatibility with Angular 10 will also be part of this issue? I get an error when I try to add ng-matero with Angular 10. 

`ewalddieser@EwiMac testprj % ng add ng-matero
Skipping installation: Package already installed
? Choose a prebuilt layout template: Dynamic
? Choose a prebuilt navigation type: Side Navigation
? Choose a prebuilt theme style: Light
? Choose a prebuilt direction option: LTR
? Set up browser animations for Angular Material? Yes
UPDATE package.json (1338 bytes)
✔ Packages installed successfully.
Cannot find module '@schematics/angular/utility/project'
Require stack:
- /Users/ewalddieser/dev/projects/CUNO/testprj/node_modules/ng-matero/utils/build-component.js
- /Users/ewalddieser/dev/projects/CUNO/testprj/node_modules/ng-matero/utils/index.js
- /Users/ewalddieser/dev/projects/CUNO/testprj/node_modules/ng-matero/ng-add/global-loader.js
- /Users/ewalddieser/dev/projects/CUNO/testprj/node_modules/ng-matero/ng-add/setup-project.js
- /Users/ewalddieser/dev/projects/CUNO/testprj/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/ewalddieser/dev/projects/CUNO/testprj/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/ewalddieser/dev/projects/CUNO/testprj/node_modules/@angular/cli/utilities/json-schema.js
- /Users/ewalddieser/dev/projects/CUNO/testprj/node_modules/@angular/cli/models/command-runner.js
- /Users/ewalddieser/dev/projects/CUNO/testprj/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng`

**Comment by nzbin** [comment]
@ewalddieser Maybe something uncompatibility with Angular 10, I will fix it.

**Comment by alan-lopez22** [comment]
I have the same problem, Hopefully, you will fix it soon :)

**Comment by nzbin** [comment]
V10 will be released in this week.

**Comment by TejasM9** [comment]
@nzbin can you add right sidebar on the data grid page ? What I need is I want to open a right side bar with search form on the data grid page. can you guide me any better way to do that. I also want to open add/edit form like that too.

**Comment by nzbin** [comment]
v10 has released.

**Comment by nzbin** [comment]
@ewalddieser v10 has released.
