### ISSUE TITLE
npm install not working after clone

### ISSUE THREAD

**Issue by Anand2805** [ng-matero/ng-matero#460]
PS C:\Workspace\ng-matero> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @angular/flex-layout@14.0.0-beta.41
npm ERR! Found: @angular/cdk@15.0.3
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"~15.0.3" from the root project
npm ERR!   peer @angular/cdk@"15.0.3" from @angular/material@15.0.3
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"~15.0.3" from the root project
npm ERR!     peer @angular/material@"15.0.3" from @angular/material-moment-adapter@15.0.3
npm ERR!     node_modules/@angular/material-moment-adapter
npm ERR!       @angular/material-moment-adapter@"~15.0.3" from the root project
npm ERR!       1 more (@ng-matero/extensions-moment-adapter)
npm ERR!     3 more (@ng-matero/extensions, ...)
npm ERR!   1 more (@ng-matero/extensions)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^14.0.0" from @angular/flex-layout@14.0.0-beta.41
npm ERR! node_modules/@angular/flex-layout
npm ERR!   @angular/flex-layout@"^14.0.0-beta.41" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/cdk@14.2.7
npm ERR! node_modules/@angular/cdk
npm ERR!   peer @angular/cdk@"^14.0.0" from @angular/flex-layout@14.0.0-beta.41
npm ERR!   node_modules/@angular/flex-layout
npm ERR!     @angular/flex-layout@"^14.0.0-beta.41" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Ara\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ara\AppData\Local\npm-cache\_logs\2022-12-24T07_56_16_781Z-debug-0.log

**Comment by nzbin** [comment]
```
npm i --force
```

**Comment by Anand2805** [comment]
worked thanks
