### ISSUE TITLE
Issue working with menu & sidenav and possibly breadcrumbs

### ISSUE THREAD

**Issue by m-mohsin-zafar** [ng-matero/ng-matero#461]
Hi, 

Thank you for such a wonderful template. I am currently facing a issue. In contrast to your default settings I don't want the application to directly land on dashboard however, I have created a separate layout for landing which further has differeent pages. To achieve this I have given default route to LandingComponent and for the dashboard I am using the route "user/dashboard". 
Consider the following chunks of code. 

`routes-routing.module.ts`
```ts
import {NgModule} from '@angular/core';
import {Routes, RouterModule} from '@angular/router';
import {environment} from '@env/environment';

import {AdminLayoutComponent} from '../theme/admin-layout/admin-layout.component';
import {AuthLayoutComponent} from '../theme/auth-layout/auth-layout.component';
import {DashboardComponent} from './dashboard/dashboard.component';
import {LoginComponent} from './sessions/login/login.component';
import {RegisterComponent} from './sessions/register/register.component';
import {Error403Component} from './sessions/403.component';
import {Error404Component} from './sessions/404.component';
import {Error500Component} from './sessions/500.component';
import {AuthGuard} from '@core';

const routes: Routes = [
  {
    path: 'user',
    component: AdminLayoutComponent,
    canActivate: [AuthGuard],
    canActivateChild: [AuthGuard],
    children: [
      {path: '', redirectTo: 'dashboard', pathMatch: 'full'},
      {path: 'dashboard', component: DashboardComponent},
      {path: '403', component: Error403Component},
      {path: '404', component: Error404Component},
      {path: '500', component: Error500Component},
      {
        path: 'details',
        loadChildren: () => import('./candidate/candidate.module').then(m => m.CandidateModule)
      },
    ],
  },
  {
    path: '',
    loadChildren: () => import('./landing/landing.module').then(m => m.LandingModule)
  },
  {
    path: 'auth',
    component: AuthLayoutComponent,
    children: [
      {path: 'login', component: LoginComponent},
      {path: 'register', component: RegisterComponent},
    ],
  },
  {path: '**', redirectTo: 'dashboard'},
];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, {
      useHash: environment.useHash,
    }),
  ],
  exports: [RouterModule],
})
export class RoutesRoutingModule {
}
```

Now, for **sideNav** to work, I understand that I need to make changes to `menu.json`. My current version is this;
```json
{
  "menu": [
    {
      "route": "user",
      "name": "dashboard",
      "type": "link",
      "icon": "dashboard"
    },
    {
      "route": "user/details",
      "name": "candidate-details",
      "type": "sub",
      "icon": "person",
      "children": [
        {
          "route": "personal",
          "name": "personal-details",
          "type": "link",
          "icon": "fingerprint"
        },
        {
          "route": "family",
          "name": "family-details",
          "type": "link",
          "icon": "people"
        },
        {
          "route": "contact",
          "name": "contact-details",
          "type": "link",
          "icon": "location_on"
        }
      ]
    }
  ]
}

```

If I don't use this `"route": "user/details",` absolute path, the navigation doesn't work. Moreover, the breadcrumb service is also not taking care for automatically generating the complete path. 

I can furnish further details, if required. 

Thanking you in anticipation.

**Comment by nzbin** [comment]
First of all, you can check the [docs](https://nzbin.gitbook.io/ng-matero/v/en-2/theming/menu) to learn the menu details. The routes config and menu's definition are closely related. 

Since you set the routes as following:
```ts
const routes: Routes = [
  {
    path: 'user',
    component: AdminLayoutComponent,
    canActivate: [AuthGuard],
    canActivateChild: [AuthGuard],
    children: [
      {path: '', redirectTo: 'dashboard', pathMatch: 'full'},
      {path: 'dashboard', component: DashboardComponent},
      ...
    ],
  },
  ...
];
```
You should define the menu in this way:
```json
{
  "menu": [
    {
      "route": "user",
      "name": "User",
      "type": "sub",
      "icon": "apps",
      "children": [
         {
           "route": "dashboard",
           "name": "Dashboard",
           "type": "link",
           "icon": "dashboard"
         },
         ...
      ]
    },
  ]
}
```

**Comment by m-mohsin-zafar** [comment]
Thank you for elaborating. I have 3 more questions to ask. 

1. Can we have multiple dashboards in this application for multiple type of users eg. Normal User, Admin, Super etc. ? If so, then how should we proceed with menu.json, and menu.service files? Some of the routes in this case would be
```
User Dashboard:
    user/dashboard
    user/dashboard/details
    user/dashboard/details/personal
    user/dashboard/details/family

Admin Dashboard:
    admin/dashboard
    admin/dashboard/overview
    admin/dashboard/details
```

2. Do we have a starter template without support for internationalization (language translation etc.)? If not how to completely clean the starter template from all such code?
3. Can you change the configuration of menu in such a way that if there are multiple levels of menu and we want to skip a level only for display purposes then it may be allowed. For example in the code that you have commented above, the menu is rendered such that a User contains a dropdown options including Dashboard however, I would just want to display Dashboard directly despite having "user" in the route. 
```
{
  "menu": [
    {
      "route": "user",
      "name": "User",
      "type": "sub",
      "icon": "apps",
      "children": [
         {
           "route": "dashboard",
           "name": "Dashboard",
           "type": "link",
           "icon": "dashboard"
         },
         ...
      ]
    },
  ]
}
```

**Comment by nzbin** [comment]
In fact, the project has no limits for your needs and maybe you should modify the source code to implement.

1. I will create lazy module to do this case. The ng-matero schematics is easy to use. You can have a try.

    ```bash
    ng g ng-matero:module user
    ng g ng-matero:page dashboard -m=user
    ng g ng-matero:page dashboard/details -m=user

    ng g ng-matero:module admin
    ng g ng-matero:page dashboard -m=admin
    ng g ng-matero:page dashboard/details -m=admin
    ```
    Then it can be visit with the route `user/dashboard` or `admin/dashboard`. Maybe some routes should be modified manually.

    ```json
    {
      "menu": [
        {
          "route": "user",
          "name": "User",
          "type": "sub",
          "icon": "apps",
          "children": [
             {
               "route": "dashboard",
               "name": "Dashboard",
               "type": "link",
               "icon": "dashboard"
             },
             ...
          ]
        },
        {
          "route": "admin",
          "name": "Admin",
          "type": "sub",
          "icon": "apps",
          "children": [
           ...
          ]
        }
      ]
    }
    ```
2. Just remove the following codes if you don't need i18n.
https://github.com/ng-matero/ng-matero/blob/1345ccf3a35a4dcfdd65e77e6a2a48f453750c6a/src/app/core/bootstrap/startup.service.ts#L39

3. I have showed a method above (`parentRoute: ['user']`). Do you have a try? I don't recommend to modify the entry route.

    ```ts
    const routes: Routes = [
      {
        path: 'user', // <= The schematics will not be working.
        component: AdminLayoutComponent,
        ...
      },
      ...
    ];
    ```
    Maybe the project can't meet all requirements. But the source code is open and you should modify it by yourself.
