### ISSUE TITLE
请问能说一下refresh token的用法吗？

### ISSUE THREAD

**Issue by winsonet** [ng-matero/ng-matero#468]
我看了代码后，应该是LOGIN后分别要从服务器返回access_token & refresh_token，然后在一定时间内会自动刷新，只是不知道这个access_token 和 refresh_token 有什么区别，服务器端要如何处理？

如果只是判断token是否正确，为什么不直接使用一个token然后继续在服务器端判断后就可以让其刷新呢？

看到你的unit test里有一个refresh token case如下：

```should refresh token when access_token is invalid and refresh_token is valid```

服务器端是如何判断 refresh_token is valid 呢？

而另一个 test case 如下：

```it should clear token when access_token is invalid and refresh token response is 401```

也不明白这个和refresh_token有什么关系，服务器返回401的话，这情况一般是无权访问，但如果能一直不断刷新，又为什么会出现无权访问的时候呢？就是什么情况下 refresh token 会返回了401？其实是和上一个test一样的问题啦。

谢谢啦！

**Comment by nzbin** [comment]
本项目的 Authentication 遵循 [RFC 6749](https://www.rfc-editor.org/rfc/rfc6749) 和 [RFC 7523](https://www.rfc-editor.org/rfc/rfc7523)，建议先了解一下这两个协议。另外，网上也有 refresh_token 的中文介绍及相关博文，可以对照着理解。

**Comment by winsonet** [comment]
哦，明白了，谢谢！
