### ISSUE TITLE
error in this command : ng g ng-matero:page <page-name> -m=<module-name>

### ISSUE THREAD

**Issue by NFTvoxies** [ng-matero/ng-matero#518]
when i use this : ng g ng-matero:page <page-name> -m=<module-name> i get this error : 

An unhandled exception occurred: Collection "ng-matero" cannot be resolved.                        
See "C:\Users\allo\AppData\Local\Temp\ng-Ae3Zqr\angular-errors.log" for further details.

**Comment by nzbin** [comment]
Do you install the npm package `ng-matero`?
