### ISSUE TITLE
UI Header's problem on Firefox

### ISSUE THREAD

**Issue by iamnobodysir** [ng-matero/ng-matero#522]
The UI Header will move down every-time if user perform an action for example click a button when the page is scrollable.

To trigger:
1. Use "Firefox"
2. Go to https://ng-matero.github.io/ng-matero/tables/remote-data
3. Scroll down to button section 
4. Press the button, the header will disappear to misalign.

I find the most obvious is using page when exploring https://ng-matero.github.io/ng-matero/tables/remote-data
Make sure is scrollable (zoom in the page) and then perform an interaction (press next page or choose page size)
<img width="1728" alt="Screenshot 2023-06-02 at 9 36 50 AM" src="https://github.com/ng-matero/ng-matero/assets/57335109/7fbf8584-f4e4-41d4-8543-70a3d71dac83">

**Comment by nzbin** [comment]
The new version 16.0.1 has fixed this issue.
