### ISSUE TITLE
i want to create my own login using my own api 

### ISSUE THREAD

**Issue by someshwarjadhav** [ng-matero/ng-matero#567]

**Comment by nzbin** [comment]
Please check the login service in `core/authentication`. If you install the app with `ng add`, you should remove the `fake-login.service` first.

https://github.com/ng-matero/ng-matero/blob/97e3b3d66393948d3a28a8e9fa7f8e1f619bd368/src/app/core/authentication/login.service.ts#L13-L15

**Comment by seyfer** [comment]
@nzbin please add docs for that there https://nzbin.gitbook.io/ng-matero/authentication

**Comment by nzbin** [comment]
@seyfer I'm sorry, I really want to update the docs but I'm busy with my work and I have many other projects to maintain.

**Comment by joshua-classen** [comment]
The login Service is saving the token in the localStorage. This is not good, because it is vulnerable to XSS Attacks.

`
login(username: string, password: string, rememberMe = false) {
    return this.loginService.login(username, password, rememberMe).pipe(
      tap(token => this.tokenService.set(token)),
      map(() => this.check())
    );
  }
  `

**Comment by nzbin** [comment]
> The login Service is saving the token in the localStorage. This is not good, because it is vulnerable to XSS Attacks.
> 
> `login(username: string, password: string, rememberMe = false) { return this.loginService.login(username, password, rememberMe).pipe( tap(token => this.tokenService.set(token)), map(() => this.check()) ); }`

Do you have any good ideas?

**Comment by joshua-classen** [comment]
> > The login Service is saving the token in the localStorage. This is not good, because it is vulnerable to XSS Attacks.
> > `login(username: string, password: string, rememberMe = false) { return this.loginService.login(username, password, rememberMe).pipe( tap(token => this.tokenService.set(token)), map(() => this.check()) ); }`
> 
> Do you have any good ideas?

Use httpOnly Flag cookies instead. The backend API can set the httpOnly Flag cookie. For example: I do this currently in dotnet c# with 
`await httpContextAccessor.HttpContext.SignInAsync(authenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties); `

My code example needs configuration settings elsewhere. For Example duration of the cookie and which claims it need.


In General it is recomended to save it as httpOnly Flaged cookie in the browser. Every professionell website, like Paypal is also only using httpOnly flag cookies for authentication stuff.

**Comment by nzbin** [comment]
> > > The login Service is saving the token in the localStorage. This is not good, because it is vulnerable to XSS Attacks.
> > > `login(username: string, password: string, rememberMe = false) { return this.loginService.login(username, password, rememberMe).pipe( tap(token => this.tokenService.set(token)), map(() => this.check()) ); }`
> > 
> > 
> > Do you have any good ideas?
> 
> Use httpOnly Flag cookies instead. The backend API can set the httpOnly Flag cookie. For example: I do this currently in dotnet c# with `await httpContextAccessor.HttpContext.SignInAsync(authenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties); `
> 
> My code example needs configuration settings elsewhere. For Example duration of the cookie and which claims it need.
> 
> In General it is recomended to save it as httpOnly Flaged cookie in the browser. Every professionell website, like Paypal is also only using httpOnly flag cookies for authentication stuff.
> 
> But Iam currently investigating how I can use AWS Cognito for my App. Unfortunetly the docs are also suggesting to save the token in the localStorage.... This is not the safest way...

Thanks for your advice! In fact, you can customize the auth logic by yourself.
