### ISSUE TITLE
Related to login

### ISSUE THREAD

**Issue by someshwarjadhav** [ng-matero/ng-matero#568]
Actually i want to use my own api of POST for login but you have used /auth/login so it gives me error routernavigation and also it givas response false 
what should i do for this .... and i want to pass username and password dynamically instead of passing static

**Comment by nzbin** [comment]
Duplicate of #567

**Comment by seyfer** [comment]
@nzbin please add docs for that there https://nzbin.gitbook.io/ng-matero/authentication
