### ISSUE TITLE
resize, hover, striped columns is not working 

### ISSUE THREAD

**Issue by himanshu09n** [ng-matero/ng-matero#570]
![image](https://github.com/ng-matero/ng-matero/assets/74291778/402d8005-0e91-4ff0-a47c-b6b51f03f989)

**Comment by himanshu09n** [comment]
@nzbin kindly assist me.

**Comment by nzbin** [comment]
I think you haven't import the styles of extensions library
https://github.com/ng-matero/ng-matero/blob/c90db24e436ac9732f48a5c4554afc1203ff6e9a/src/styles/_app-theme.scss#L20
Please check the online demo https://ng-matero.github.io/ng-matero/tables/kitchen-sink

**Comment by himanshu09n** [comment]
[ng-matero.zip](https://github.com/ng-matero/ng-matero/files/12597317/ng-matero.zip)
i tried to import the styles of extensions library but still not working. kindly assist me on attached project.

**Comment by himanshu09n** [comment]
resolved this problem. thank you so much for your support.

**Comment by Harsh-Singh-Rajput** [comment]
Hi @himanshu09n  @nzbin , I am also facing the same issue. Can you please help me how can I fix this, I am not able to understand how and where to import that package. I have installed ng-matero package and used data grid. Now what steps I had to follow so that hover and striped get starts working?

**Comment by Harsh-Singh-Rajput** [comment]
It is working now, I had added the default azure blue theme instead of ng-matero theme
