### ISSUE TITLE
Circular Dependency in the sidemenu nav-accordion directives

### ISSUE THREAD

**Issue by SJKaran** [ng-matero/ng-matero#579]
The following error pops up when I try running my app:

![image](https://github.com/ng-matero/ng-matero/assets/87128168/c74d531f-18fe-46d7-8053-223feda264b2)

I checked for circular dependencies using npx madge, and it showed the following:

```
✖ Found 1 circular dependency!

1) src/app/theme/sidemenu/nav-accordion-item.directive.ts > src/app/theme/sidemenu/nav-accordion.directive.ts
```

And indeed there seems to be a circular dependency. where the NavAccordionDirective is dependent on NavAccordionItemDirective, and vice versa.

Any help in solving this error would be appreciated.

**Comment by nzbin** [comment]
I'm not sure why this happened. In fact, you can remove the `NavAccordionItemDirective` here and use `any` instead.

https://github.com/ng-matero/ng-matero/blob/c2994a05771fd08653584756764ed7b4d305ce1a/src/app/theme/sidemenu/nav-accordion.directive.ts#L5
