### ISSUE TITLE
Not able to setup matero

### ISSUE THREAD

**Issue by edgarjoao** [ng-matero/ng-matero#583]
Hello there,
I've trying to install matero template but not luck, I'm following the steps described in your wikil

<img width="441" alt="image" src="https://github.com/ng-matero/ng-matero/assets/2808356/ef3c1d1c-9835-44cb-a090-43a80a736873">

After install, I don't see any layout created :( 

<img width="243" alt="image" src="https://github.com/ng-matero/ng-matero/assets/2808356/b89e1ba6-043d-4308-b333-409d83684f77">

Also not able to add a new module

ng g ng-matero:module users
<img width="318" alt="image" src="https://github.com/ng-matero/ng-matero/assets/2808356/de30112e-d939-4781-9983-83db7a56cb78">

**Comment by nzbin** [comment]
I'm sorry, there has a small bug for v16. I have fixed it, please try `ng add ng-matero` again.

**Comment by edgarjoao** [comment]
Hi @nzbin 
it's working now, thank you !
