### ISSUE TITLE
flex-layout no longer supported by Angular

### ISSUE THREAD

**Issue by edgarjoao** [ng-matero/ng-matero#584]
Hi Matero team,
The Angular team no longer publishes new releases for flex-layout, are you going to look for some other alternatives?

Regards,
Edgar

**Comment by nzbin** [comment]
First of all, you can still use the latest version of flex-layout. In addition, the ng-matero provide a lot of CSS helpers. You can have a try.
https://ng-matero.github.io/ng-matero/utilities/css-grid
