### ISSUE TITLE
Display bug on chrome

### ISSUE THREAD

**Issue by corentinclichy** [ng-matero/ng-matero#593]
Hello,

Thanks for the good work on the extensions. 

I have a problem when using chart inside mat-card wiht the drawer. 

When I open and close a drawer, I get part of the chart hide. This bug only occur when using google chrome.
Do you have any idea on what's causing that behavior ? $

When I hover hidden part, it disappear and I am able to see the full card.

Photo of the issue:
![image](https://github.com/ng-matero/ng-matero/assets/8075501/df8c3578-400b-4b6f-98d9-851bfd4b190b)

Thanks a lot for your help

**Comment by nzbin** [comment]
I will close this issue as there has a same one https://github.com/ng-matero/extensions/issues/256

**Comment by corentinclichy** [comment]
Yes, I realized it was more accurate to put it on the extensions repo
