### ISSUE TITLE
issue for mtx-grid

### ISSUE THREAD

**Issue by someshwarjadhav** [ng-matero/ng-matero#595]
how to use badge at the mat-icon in mtx-grid ?

**Comment by nzbin** [comment]
https://ng-matero.github.io/extensions/components/grid/overview#custom-cell-template-2

**Comment by someshwarjadhav** [comment]
i used this before  -
**badge: {
            content: 1,
            size: 'small',
          },** 
but how to declare badge in interface.ts

**Comment by nzbin** [comment]
> i used this before - **badge: { content: 1, size: 'small', },** but how to declare badge in interface.ts

I don't quite understand, the badge only support with button type

```ts
columns = [
  {
    header: '...,'
    field: '...',
    buttons: [
      {
        type: 'icon',
        text: 'delete',
        icon: 'delete',
        color: 'warn',
        badge: {
          content: '...',
          description: '...',
          color: '...',
          position: '...',
          size: '...',
          overlap: '...',
          disabled: '...',
          hidden: '...',
        }
      },
    ],
  }
]
```

**Comment by someshwarjadhav** [comment]
how to declare  badge: {
          content: '...',
          description: '...',
          color: '...',
          position: '...',
          size: '...',
          overlap: '...',
          disabled: '...',
          hidden: '...',
        } this badge in interfaces.d.ts

**Comment by nzbin** [comment]
> how to declare badge: { content: '...', description: '...', color: '...', position: '...', size: '...', overlap: '...', disabled: '...', hidden: '...', } this badge in interfaces.d.ts

I can't understand your question, can you provide more details?
