### ISSUE TITLE
Is it possible not to use external resource links

### ISSUE THREAD

**Issue by expcat** [ng-matero/ng-matero#60]
```html
<link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap">
```
Some areas cannot access the googleapis domain.
And it is possible to deploy the project in an environment without an external network.

**Comment by nzbin** [comment]
If you dont need it, you can delete it manually. I have set a common font family for Material, so it won't make much difference.
