### ISSUE TITLE
changing theme color doesn't work in AppSettings

### ISSUE THREAD

**Issue by AliAUZ** [ng-matero/ng-matero#61]
Hi when I change the theme from 'light' to 'dark' in the settings.ts (default)  it doesn't work 
after save and reload the app (ng serve)
in the previous version, it was working

**Comment by nzbin** [comment]
Is it the starter(`ng add ng-matero`) has this issue?

**Comment by AliAUZ** [comment]
I have problem with "ng add ng-matero" so I had to download and try it 
when I use the starter (ng add ng-matero) then I get these errors

> 811 error code ELIFECYCLE
> 812 error errno 1
> 813 error abcd@0.0.0 postinstall: `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`
> 813 error Exit status 1
> 814 error Failed at the abcd@0.0.0 postinstall script.
> 814 error This is probably not a problem with npm. There is likely additional logging output above.

and some error in the terminal 

![error2](https://user-images.githubusercontent.com/29033729/90763209-9d460f00-e329-11ea-9783-791b37b8c3da.jpg)
![error1](https://user-images.githubusercontent.com/29033729/90763216-9fa86900-e329-11ea-9812-08288f1eef06.jpg)

**Comment by AliAUZ** [comment]
I've upgraded to ver 10 and now is working but the same issue for them color 
If I change it in the 

`export const defaults: AppSettings = {
  navPos: 'side',
  theme: 'dark',
  dir: 'ltr',
  showHeader: true,
  headerPos: 'fixed',
  showUserPanel: true,
  sidenavOpened: true,
  sidenavCollapsed: false,
  language: 'en-US',
};`

as well, still the same issue

**Comment by nzbin** [comment]
I have fixed this issue, thanks for your advice.

https://github.com/ng-matero/ng-matero/blob/56a35f5e1307bc96c569ccd1739f83aeb3c6ef30/src/app/theme/admin-layout/admin-layout.component.ts#L94-L95

**Comment by AliAUZ** [comment]
Yes !! now it's working and the direction is working as well !! (" dir: 'ltr',")

for the language in the settings.ts if I set "language: 'en-US'," to "zh-CN" 
and then it doesn't change the language in the startup 

Do I need to set it anywhere else?
thx
