### ISSUE TITLE
Log in with another user after previous log in and log out with a different user does not trigger startup load

### ISSUE THREAD

**Issue by seyfer** [ng-matero/ng-matero#610]
Log in with one user, log out, log in with another user - startup won't trigger,
therefore leaving previous user permissions and menu loaded, until you refresh the page

the problem is with this change chain

TokenService
`private change$ = new BehaviorSubject<BaseToken | undefined>(undefined);`

AuthService
```
private change$ = merge(
    this.tokenService.change(),
    this.tokenService.refresh().pipe(switchMap(() => this.refresh())),
  ).pipe(
    tap(() => console.log('token change')),
    switchMap(() => this.assignUser()),
    share(),
  );
```

StartupService
```
load() {
    return new Promise<void>((resolve, reject) => {
      this.authService
        .change()
        .pipe(
          tap(user => console.log('startup', user.role)),
          tap(user => this.setPermissions(user)),
          switchMap(() => this.authService.menu()),
          tap(menu => this.setMenu(menu)),
        )
        .subscribe({
          next: () => resolve(),
          error: () => resolve(),
        });
    });
  }
```

Fe. I log in with a user Admin that has a role Admin and own menu
I can see that the save() triggered tokenService.change() with the new token, therefore triggering a change in auth service, triggering StartupService.load, and loads menu and permissions

then I log out. 
I can see that save() triggered tokenService.change() with `undefined`, therefore triggering a change in auth service, triggering StartupService.load with {} user

I log in with another user with the role USER
The startup is not getting triggered, therefore it does not load a new menu and permissions,
therefore I still see ADMIN menu and have permissions. 

for some reason on the second login, even though a new token was set there
`this.change$.next(this.token);` the `change$` not triggering and therefore not triggering menu and permissions loading.

I made no changes to the original install on NG-MATERO. 

@nzbin please check asap, this is critical.

**Comment by seyfer** [comment]
@nzbin to fix this, I had to do the following

in AuthService I added
```
setUser(user: AuthUser) {
    this.user$.next(user);
  }
```

to StartupService I added this method
```
loadProgrammatically() {
    this.apiLoginService.me().pipe(
      tap(user => this.authService.setUser(user)),
      tap(user => this.setPermissions(user)),
      switchMap((user) => this.authService.menu(user)),
      tap(menu => this.setMenu(menu)),
    ).subscribe();
  }
```

which does the same as load() method

then in LoginComponent I call this method in the login pipe
```
login() {
    this.isSubmitting = true;

    this.auth
      .login(this.email.value, this.password.value, this.rememberMe.value)
      .pipe(filter(authenticated => authenticated))
      .subscribe({
        next: () => {
          this.router.navigateByUrl('/').then(() => {
            this.startupService.loadProgrammatically();
          });
        },
```

in this way it works, I just do setup after login request, because `change()` of tokenService and authService won't trigger...

maybe it broke after a recent Angular update release? idk.

**Comment by nzbin** [comment]
Which version do you use? I don't find any issues for v16.

**Comment by seyfer** [comment]
@nzbin I use the most recent version, installed a week ago following `ng add` approach, as per docs.

**Comment by seyfer** [comment]
@nzbin even with the same user StartupService.load() won't trigger. 
just log-in, log-out several times without refreshing the page in the browser, add console.log to startup pipe, you will see
but if this is the same user - there is no problem, because menu and permissions are the same
if another user logged in - it's permissions and menu won't load as startupservice.load won't trigger, and that user has permissions and menu form a user that logged in first.

**Comment by nzbin** [comment]
> @nzbin even with the same user StartupService.load() won't trigger. just log-in, log-out several times without refreshing the page in the browser, add console.log to startup pipe, you will see but if this is the same user - there is no problem, because menu and permissions are the same if another user logged in - it's permissions and menu won't load as startupservice.load won't trigger, and that user has permissions and menu from a user that logged in first.

Yes, it's correct. The `authService.change()` will be implemented automatically only when the token (JWT) changed.

**Comment by nzbin** [comment]
Sorry for late reply. Please check the demo site and test it.

https://github.com/ng-matero/ng-matero/blob/7b9df964fa412e37b3aa8a6aa7f2b752478c55a0/src/app/shared/in-mem/in-mem-data.service.ts#L87-L105

1. Open chrome `devtools` -> `network`
2. Logout and login with another user (`recca0120`)
3. Check the `network` -> `Fetch/XHR`
4. You can find that it will get the `menu.json`
