### ISSUE TITLE
[BUG] Notification drop-down click targets are too small

### ISSUE THREAD

**Issue by russelporosky** [ng-matero/ng-matero#629]
The click target appears to only be the `a` link text itself. When you hover, the entire `mat-list-item` block animates and the cursor changes to the pointer, suggesting that the entire `mat-list-item` should be clickable. Clicking anywhere within the `mat-list-item` that is _not_ the link text does nothing except close the notification drop-down.

<img width="359" alt="image" src="https://github.com/ng-matero/ng-matero/assets/6520433/96363e3a-305d-4a21-830f-c4daa80ec007">

This appears to be the only list of links that behaves this way, so it is inconsistent with the other navigation lists and should be corrected.

**Comment by nzbin** [comment]
Thanks for your advice, it's only used for demo. I think you can improve it by yourself.
