### ISSUE TITLE
Cannot find module '@schematics/angular/private/components.js'

### ISSUE THREAD

**Issue by NutellaTorte** [ng-matero/ng-matero#643]
Hello,

I get following error on the `ng add` schematic:

`Cannot find module '/Users/path-to-my-project/my-frontend/node_modules/@schematics/angular/private/components.js'`

Steps to reproduce:

```shell
$ npm i -g @angular/cli

$ ng version # output is 17.2.0

$ ng new my-frontend

$ ng add ng-matero
```
After step "Installing packages" this error occurs. I think it is because of your `schematics/ng-add/setup-project.ts`. You are importing the following functions:

```ts
import {
  addFunctionalProvidersToStandaloneBootstrap,
  callsProvidersFunction,
  importsProvidersFrom,
} from '@schematics/angular/private/components';
```

These functions are deprecated and I think they removed this functions on V17. See [here](https://github.com/angular/angular-cli/commit/6a4d733ddaf67c0b93f48ff39cd2a987dcd2b024).

I think it could be fixed by changing the imports to:

```ts
import {
  addFunctionalProvidersToStandaloneBootstrap,
  callsProvidersFunction,
  importsProvidersFrom,
} from '@schematics/angular/private/standalone';
```

**Comment by nzbin** [comment]
17.0.2 has fixed the error, please try again.

**Comment by NutellaTorte** [comment]
I can confirm that this fixes this error.

Thank you and have a nice day 😊
