### ISSUE TITLE
Add support for Angular v18

### ISSUE THREAD

**Issue by Guilherme27Borges27** [ng-matero/ng-matero#678]
Hey there,

Angular has released version 18, and after updating my project, I saw that ng-matero is not compatible. 
Could you let me know when ng-matero plans to update its components to be compatible with Angular version 18?

Thank you!

**Comment by nzbin** [comment]
The v18 will be released this week, all styles have been re-designed for Material 3, please stay tuned.

**Comment by nzbin** [comment]
The v18 has released! New UI for Material 3.

![Xnip2024-06-23_11-49-20](https://github.com/ng-matero/ng-matero/assets/20625845/4ea10dbc-602c-4501-8348-6c05ae256487)

![Xnip2024-06-23_13-14-31](https://github.com/ng-matero/ng-matero/assets/20625845/5a36a6f9-4565-4cf4-a2db-5dfbaa3d052d)

![Xnip2024-06-23_11-50-08](https://github.com/ng-matero/ng-matero/assets/20625845/8deb215f-4e1e-47fe-af23-d65c9becd269)
