### ISSUE TITLE
is this file /ng-matero/schematics/utils/theming.ts auto generated?

### ISSUE THREAD

**Issue by navegador5** [ng-matero/ng-matero#69]
hi, i plan to add a small feature for quick-search-and-locate mod-com-srv-dir-pipe in ng-matero , but i am NOT sure this file :
`      **/ng-matero/schematics/utils/theming.ts**`
is it auto generated by angular-cli ?
  ` i need to modify one function in it to implement this small feature`

**Comment by navegador5** [comment]
I did a independant project to do routing-module auto generate finally:
    https://www.npmjs.com/package/nv-angular-routing
I did not undertand schematics well ,so failed to intergrated it into matero

**Comment by nzbin** [comment]
If you have any other questions, you can reopen this issue.
