### ISSUE TITLE
后退的时候能否不刷新上个页面

### ISSUE THREAD

**Issue by mu0641** [ng-matero/ng-matero#7]
后退的时候能否不刷新上个页面

**Comment by mu0641** [comment]
在输入框里面填好数据后，点击别的页面后退回来，用户之前填写的数据会被清空

**Comment by damingerdai** [comment]
> 在输入框里面填好数据后，点击别的页面后退回来，用户之前填写的数据会被清空

这样的业务场景应该由实际的开发做缓存吧？

**Comment by nzbin** [comment]
路由跳转会重新加载组件，所以肯定会刷新视图，数据保存可以考虑其它方式

**Comment by mu0641** [comment]
好的，明白了
