### ISSUE TITLE
Breadcrumb does not recognize route changes

### ISSUE THREAD

**Issue by lukemper** [ng-matero/ng-matero#706]
Hello,

I recognize that the breadcrumb doesn't listen to route changes. For example, if you switch between the overview and edit profile on the profile page, the breadcrumb does not change.

I have another question: Can I open pull requests for possible features and bug fixes?
I like your template and i'm using some components from your template. Maybe I can help you.

Have a nice day!

**Comment by nzbin** [comment]
Of course, I will be glad if you can give a PR.

**Comment by lukemper** [comment]
Do you have a convention for branches?
Should I create a new branch or using an existing branch?

**Comment by nzbin** [comment]
> Do you have a convention for branches? Should I create a new branch or using an existing branch?

https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Comment by nzbin** [comment]
18.0.2 has fixed.
