### ISSUE TITLE
Tag color not applying

### ISSUE THREAD

**Issue by enockkim** [ng-matero/ng-matero#707]
```
true: { text: 'Yes', color: 'red-100' },
false: { text: 'No', color: 'green-100' },
```
        
Neither is working. 
        
I cloned the repo and ran ng serve -o , i changed nothing
        
Page: http://localhost:4200/tables/remote-data

Same issue on different browsers, ive tried both Chrome v126.0.6478.128 and Firefox v126.0.1 
        
![image](https://github.com/user-attachments/assets/076ef068-8d46-4cb0-bb75-90bcb3e92184)

**Comment by nzbin** [comment]
I'm sorry, the v18 color helpers have changed.
https://ng-matero.github.io/ng-matero/utilities/css-helpers

**Comment by enockkim** [comment]
Appreciated
