### ISSUE TITLE
user login & register form submit functions

### ISSUE THREAD

**Issue by jsdnhk** [ng-matero/ng-matero#72]
As I saw there contains login and register form with submit button.
However, in login submit function cannot find the part of posting HTTP auth requests and handling returned jwt in code.
Also didn't see the register submit function.
May suggest the place to change or how to implement that out? Thanks a lot.

**Comment by nzbin** [comment]
If you need HTTP requests, you can add a service to login or register folder.

**Comment by jsdnhk** [comment]
thanks and may provide some example for it if using JWT auth via REST API?
