### ISSUE TITLE
ngx-mask integration

### ISSUE THREAD

**Issue by eexposito** [ng-matero/ng-matero#722]
Is it possible to integrate ngx-mask or some other input masking library? I copied over exactly what I did for another project and keep getting: 

`NG8002: Can't bind to 'mask' since it isn't a known property of 'input'. [plugin angular-compiler]`

Is there a specific way it needs to be added?

Thanks

**Comment by eexposito** [comment]
I went the angular module route

`@NgModule({
  imports: [
      NgxMaskDirective, NgxMaskPipe
  ],
  providers: [provideNgxMask()]
})`

**Comment by nzbin** [comment]
I'm sorry, I need more details, please give me an online example.

**Comment by eexposito** [comment]
I got it working by changing the login component to a stand alone component.
