### ISSUE TITLE
I meet a very weird issue ,If the data returned by the program contains the code field, an error will be reported.

### ISSUE THREAD

**Issue by HelloReboot** [ng-matero/ng-matero#724]
<img width="721" alt="image" src="https://github.com/user-attachments/assets/d4a1a5ea-63ee-4e3c-bfb3-923560db72a6">

<img width="826" alt="image" src="https://github.com/user-attachments/assets/016d8c1f-1f7c-432a-aacd-15457d71850f">
<img width="1334" alt="image" src="https://github.com/user-attachments/assets/2e21fcf9-7bf4-4de3-a755-e0e4a6dfd5e9">

 however. if the return data including a code columns  the programs will run into the error {}.but console  log can not catch anything.
anyone can help ? 

return data like that :
     {"code":1}.

**Comment by nzbin** [comment]
https://github.com/ng-matero/ng-matero/blob/178ff35bb5f2a8762a0aac1da73722b7a7808512/src/app/core/interceptors/default-interceptor.ts#L24-L38

You can get the response with `catchError`, please have a try.

```ts
this.http.post(...).pipe(
  catchError(err => {
    console.log(err);
    return throwError(() => err);
  })
).subscribe(...)
```
