### ISSUE TITLE
Token is not passed with the request headers

### ISSUE THREAD

**Issue by moees** [ng-matero/ng-matero#750]
I want to make some requests to a backend, specially the "/me" where I call "localhost:8888/api/v1/user/current". 

```ts
me() {
    return this.http.get<User>(`${environment.apiUrl}/api/v1/user/current`);
  }
```

Following the  documentation I changed this in the login.interceptor.ts. and I also changed the token.service.ts as the following:

```ts
if (this.tokenService.valid() && (this.shouldAppendToken(req.url) || req.url.includes("/api"))) {
      return next
        .handle(
          req.clone({
            headers: req.headers.append('Authorization', this.tokenService.getBearerToken()),
            withCredentials: true,
          })
        )
``` 

But I still see that the request token is missing in the call to the backend. I don't know where the token is removed or the headers are overrided. I'm using v18.0.2. Can somone help.

**Comment by nzbin** [comment]
I think you should check this condition and remove it to try again.
https://github.com/ng-matero/ng-matero/blob/cf6c57759d54ca08d55fe3840291ff2614fa1e58/src/app/core/interceptors/token-interceptor.ts#L49-L51

```ts
if (this.tokenService.valid() && req.url.includes("/api")) {
...
}
```
