### ISSUE TITLE
The sidebar menu didn't collapse when hovering.

### ISSUE THREAD

**Issue by R3JMW** [ng-matero/ng-matero#95]
Hey, I'm glad it's a specific solution expect the PrimeNG for Angular.
It's a great job for all the components was been designed and implemented by yourself.

Here's a tiny issue for the sidebar behavior. You can see when the sidebar menu collapse but the sub level menu didn't collapse which looks strange.
![image](https://user-images.githubusercontent.com/45484888/116555476-06f1d080-a92f-11eb-9787-a37ba3a6400a.png)

**Comment by nzbin** [comment]
Duplicate of #56
